[build]
  command = "npm install --legacy-peer-deps && ng build --configuration production --no-build-optimizer"
  publish = "dist/my-financial-twin/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
