[build]
  command = "npm run build:ssr"
  publish = "dist/my-financial-twin/browser"
  functions = "dist/my-financial-twin/server"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@angular/platform-server"]
